### PR TITLE
[WIP ]Integration tests

### PR DESCRIPTION
**Pull request by dhuppenkothen**
Initial integration tests for the instruments for which I have test data sets. The test data is currently not included so this won't work yet.

@eblur, @abigailStev : We need to make a decision whether to include some of the test data files with the repo? Since you produced the data files, I don't want to do that without having your permission. 

The only slightly larger data set included is Chandra/HETG, and I think for that we only need a subset in the repo (if it works for one, it'll also work for the other three). Thoughts?

### CODE REVIEW

**Comment by abigailStev** [comment]
@dhuppenkothen I'm happy to have the test data I created included in the repo!

**Comment by eblur** [comment]
My only worry is the issue of putting large-ish fits files on version control.  I would rather put a tarball of the test data somewhere downloadable for running the tests.  Will that be an issue with travis?

**Comment by dhuppenkothen** [comment]
@eblur What's your worry with having these files under version control? The total files are ~18MB, which doesn't seem huge.
I would worry about them if they were binaries that change all the time for some reason (which can then quickly blow up the repo size), but I'm assuming our test data should be pretty static?

**Comment by eblur** [comment]
I don't have enough expertise to fully answer this question; I'm just under the impression that putting any fits files under version control is a big faux pas... so much so that I had to go through and rewrite git history on the astropy tutorials just to get rid of the "memory" of a fits file that I used in an ipynb.  (To be fair, I'm pretty sure that file was larger than ~18 MB).

It seems that, if a file can't be diffed easily (which I think is true for FITS files), then a copy is made with each checkout.  This seems to be unique to git and not all version control systems.
http://ask.metafilter.com/281456/Best-practices-for-verson-control-with-binary-files

Another article on the topic:
https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/

Am I wrong in my understanding that FITS files can't be diffed?

**Comment by eblur** [comment]
Putting this here for reference: "Storing large binary files in git repositories"
http://blog.deveo.com/storing-large-binary-files-in-git-repositories/

**Comment by dhuppenkothen** [comment]
Thanks for this!

Yeah, you're right. We should only really be putting binary files under version control if we're *sure* they're not going to change in the future (and I suppose the response files actually could change)? 

I'm currently exploring alternatives; will keep you posted.

**Pull request merged**
